// <auto-generated />
using System;
using HHBAspire.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HHBAspire.ApiService.Migrations
{
    [DbContext(typeof(BethanyDataContext))]
    [Migration("20250811023945_FixMinistryMapping, MakeInfoApiOwned")]
    partial class FixMinistryMappingMakeInfoApiOwned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HHBAspire.Shared.Data.MinistryObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("SiteInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SiteInfoId");

                    b.HasIndex("SiteInfoId", "ParentId");

                    b.ToTable("Ministries");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.NewsObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTimeOffset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("SiteInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiteInfoId", "DateTime");

                    b.ToTable("News");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.ServiceObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiteInfoId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.SiteInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SiteInfos");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.SlideObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Expand")
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<int>("SiteInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiteInfoId", "Headline");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.TeamMemberObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Facebook")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("Linkedin")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int>("SiteInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("X")
                        .HasColumnType("text");

                    b.Property<string>("Youtube")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteInfoId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.ThumbnailObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SiteInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteInfoId", "Type");

                    b.ToTable("Thumbnails");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.MinistryObject", b =>
                {
                    b.HasOne("HHBAspire.Shared.Data.MinistryObject", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HHBAspire.Shared.Data.SiteInfo", "SiteInfo")
                        .WithMany("Ministries")
                        .HasForeignKey("SiteInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("SiteInfo");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.NewsObject", b =>
                {
                    b.HasOne("HHBAspire.Shared.Data.SiteInfo", "SiteInfo")
                        .WithMany("News")
                        .HasForeignKey("SiteInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteInfo");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.ServiceObject", b =>
                {
                    b.HasOne("HHBAspire.Shared.Data.SiteInfo", "SiteInfo")
                        .WithMany("Services")
                        .HasForeignKey("SiteInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteInfo");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.SiteInfo", b =>
                {
                    b.OwnsOne("HHBAspire.Shared.Data.ApiLinkObject", "Api", b1 =>
                        {
                            b1.Property<int>("SiteInfoId")
                                .HasColumnType("integer");

                            b1.Property<string>("GoogleMap")
                                .HasColumnType("text");

                            b1.Property<string>("YoutubeChannel")
                                .HasColumnType("text");

                            b1.HasKey("SiteInfoId");

                            b1.ToTable("SiteInfos");

                            b1.WithOwner()
                                .HasForeignKey("SiteInfoId");
                        });

                    b.OwnsOne("HHBAspire.Shared.Data.BasicInfoObject", "Info", b1 =>
                        {
                            b1.Property<int>("SiteInfoId")
                                .HasColumnType("integer");

                            b1.Property<string>("AboutUsBethany")
                                .HasColumnType("text");

                            b1.Property<string>("AboutUsSDA")
                                .HasColumnType("text");

                            b1.Property<string>("Address")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Organization")
                                .HasColumnType("text")
                                .HasColumnName("Organization");

                            b1.Property<string>("Phone")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("SiteInfoId");

                            b1.ToTable("SiteInfos");

                            b1.WithOwner()
                                .HasForeignKey("SiteInfoId");
                        });

                    b.Navigation("Api")
                        .IsRequired();

                    b.Navigation("Info")
                        .IsRequired();
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.SlideObject", b =>
                {
                    b.HasOne("HHBAspire.Shared.Data.SiteInfo", "SiteInfo")
                        .WithMany("Slides")
                        .HasForeignKey("SiteInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteInfo");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.TeamMemberObject", b =>
                {
                    b.HasOne("HHBAspire.Shared.Data.SiteInfo", "SiteInfo")
                        .WithMany("TeamMembers")
                        .HasForeignKey("SiteInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteInfo");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.ThumbnailObject", b =>
                {
                    b.HasOne("HHBAspire.Shared.Data.SiteInfo", "SiteInfo")
                        .WithMany("Thumbnails")
                        .HasForeignKey("SiteInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteInfo");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.MinistryObject", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HHBAspire.Shared.Data.SiteInfo", b =>
                {
                    b.Navigation("Ministries");

                    b.Navigation("News");

                    b.Navigation("Services");

                    b.Navigation("Slides");

                    b.Navigation("TeamMembers");

                    b.Navigation("Thumbnails");
                });
#pragma warning restore 612, 618
        }
    }
}
